### ISSUE TITLE
Best model for Persian Speech Recognition

### ISSUE THREAD

**Issue by MelikaBahmanabadi** [s3prl/s3prl#126]
Hi, 
What is the best model for Persian Speech Recognition?

**Comment by leo19941227** [comment]
Hi,

Since currently most of the Speech SSL pretrained models are pretrained on English, so for Persian I think the only choice will be the multilingual version of wav2vec2. You can use the following line to load it:

```
model_with_pretrained_weights = torch.hub.load('s3prl/s3prl', 'wav2vec2_xlsr')
```

`model_with_pretrained_weights` is just a regular nn.Module and here is the [I/O format](https://github.com/s3prl/s3prl/tree/master/upstream#1-for-all-interface).

**Comment by MelikaBahmanabadi** [comment]
> Hi,
> 
> Since currently most of the Speech SSL pretrained models are pretrained on English, so for Persian I think the only choice will be the multilingual version of wav2vec2. You can use the following line to load it:
> 
> ```
> model_with_pretrained_weights = torch.hub.load('s3prl/s3prl', 'wav2vec2_xlsr')
> ```
> 
> `model_with_pretrained_weights` is just a regular nn.Module and here is the [I/O format](https://github.com/s3prl/s3prl/tree/master/upstream#1-for-all-interface).

Thanks a lot leo19941227. Would you please share a sample code with wa2vec2_xlsr for speech recognition? I am beginner and don`t know how to use it exactly.

**Comment by leo19941227** [comment]
Hi,

I think you can start from training an ASR on LibriSpeech following [these step](https://github.com/s3prl/s3prl/tree/master/downstream#asr-automatic-speech-recognition), and then dive into the `downstream/asr/dataset.py` to change the transcriptions and the dictionary.

Here is an command example:
```
python3 run_downstream.py -m train -u wav2vec2_xlsr -d asr -n HelloWorld
```

**Comment by MelikaBahmanabadi** [comment]
> Hi,
> 
> I think you can start from training an ASR on LibriSpeech following [these step](https://github.com/s3prl/s3prl/tree/master/downstream#asr-automatic-speech-recognition), and then dive into the `downstream/asr/dataset.py` to change the transcriptions and the dictionary.
> 
> Here is a command example:
> 
> ```
> python3 run_downstream.py -m train -u wav2vec2_xlsr -d asr -n HelloWorld
> ```
> 
> The command will train an ASR on LibriSpeech (English) with the multilingual wav2vec2_xlsr.

Thanks a lot. What about fine-tune? How can I fine-tune wav2vec2_xlsr with Persian audio dataset?

**Comment by leo19941227** [comment]
Hi,

The `run_downstream.py` script default will extract multiple hidden states from the pretrained model and learn a weighted-sum for downstream tasks. You can use this command to get only the last layer representation and finetune the entire pretrained model.

```
python3 run_downstream.py -m train -u wav2vec2_xlsr -d asr -n HelloWorld --upstream_feature_selection last_hidden_state --upstream_trainable
```

`--upstream_feature_selection` equals to `-s`
`--upstream_trainable` equals to `-f`

**Comment by leo19941227** [comment]
Since finetuning the entire pretrained model need lots of GPU memory, and we will end up using very small batch size on a single GPU. Typically we will need distributed training. You can refer to [here](https://github.com/s3prl/s3prl/tree/master/downstream#distributed-training) for a general usage. The command pattern adjustment is agnostic to downstream task.
