### ISSUE TITLE
SLOW - Auto resume from checkpoint ?

### ISSUE THREAD

**Issue by Enescigdem** [s3prl/s3prl#168]
Hi,
I conduct ASR training with my own data. But dataset preparation takes a lot of time for every start even if resume from the checkpoint. How can I avoid this? 
Thanks in advance

**Comment by leo19941227** [comment]
Hi,

Unfortunately we always wait for the dataset preparation since it typically takes only a few seconds at my side...
If you wish to avoid this perhaps you can implement some caching mechanism in the dataset's `__init__` function.
Or perhaps you can try to set the default worker num to be larger.

https://github.com/s3prl/s3prl/blob/205cdc3abd7d56169a98557bf865230a661a06de/s3prl/downstream/asr/dataset.py#L157-L164
