### ISSUE TITLE
The documented fairseq installation is not compatible with ASR decoding

### ISSUE THREAD

**Issue by Enescigdem** [s3prl/s3prl#169]
Hi,
I noticed  decoder type is NONE in _downstream/asr/config.yaml_ .What possible types of decoders can be used? I checked the flashlight link but I could not understand.

**Comment by leo19941227** [comment]
Hey, you can use the `kenlm` for `decoder_type` after you install follow the decoder installation steps in downstream/README.md.
Flashlight toolkit and kenlm can sometimes be complicated to install them right, you can also ask here for help if you can't get reasonable decoding results. I might have some experience to share with you.

**Comment by Enescigdem** [comment]
Hi,
I want to ask difference between KENLM path and lexicon path ?

**Comment by leo19941227** [comment]
KenLM path is the 4-gram arpa LM released along with LibriSpeech.
lexicon path is the characters -> word mapping which we want to consider during the decoding.

**Comment by Enescigdem** [comment]
> KenLM path is the 4-gram arpa LM released along with LibriSpeech.
> lexicon path is the characters -> word mapping which we want to consider during the decoding.

Thank you

**Comment by Enescigdem** [comment]
Hi,
I faced the error below,
**_from examples.speech_recognition.w2l_decoder import W2lViterbiDecoder
ModuleNotFoundError: No module named 'examples'_**

**Comment by leo19941227** [comment]
Oh,

This is really an issue. Please first consider installing fairseq via `pip install -e ./` instead of the one documented at the README.md.
This is because the `examples` is not considered as a part of the fairseq package
https://github.com/pytorch/fairseq/blob/1f7ef9ed1e1061f8c7f88f8b94c7186834398690/setup.py#L216-L221
But you can still use the files inside `examples` via editable installation.
