### ISSUE TITLE
Unordered input when testing speaker frame classification

### ISSUE THREAD

**Issue by toco2270853** [s3prl/s3prl#184]
Dear developer, 
  I'm currently evaluating pretrained Tera model on Librispeech 
speaker classification task(by frame). When using original s3prl script, the result is similar to what paper report. But when I evaluate the task using my own script, I find a big performance gap. After checking my script output the same feature as s3prl script, I finally find that the bug comes from that I use unordered(length) input to form batch data. 
  I run the task again with my own configuration using s3prl script, with/without using random order input to form batch, and similar performance drop is found. 

I add following code below this line
https://github.com/s3prl/s3prl/blob/8e3e995dd72d368e47a5410f2f6f1aaf47fc65ab/s3prl/downstream/speaker_linear_utter_libri/dataset.py#L60

    tmp = list(zip(X, X_lens))
    random.Random(4).shuffle(tmp)
    X, X_lens = zip(*tmp)
    X = list(X)
    X_lens = list(X_lens)

and downstream configuration change is:

    total_steps: 40000
    lr: 0.0025
    train_batch_size: 3
    eval_batch_size: 3

**Comment by andi611** [comment]
Hi,

I presume the performance drop is caused by the padded zeros.

Please take a look at these two [lines](https://github.com/s3prl/s3prl/blob/8e3e995dd72d368e47a5410f2f6f1aaf47fc65ab/s3prl/downstream/speaker_linear_frame_libri/expert.py#L50-L51).
In our original implementation, we use ordered length input (bucketing), as a result, there is almost no padding needed (only in extremely rare cases/batches).
However, if you do not order the input, there will be lots of padding. Thus you have to use a mask when you compute the loss and take extra care of the padded frames. (This part we did not implement.)

Hope this can help you debug your script.

**Comment by toco2270853** [comment]
Thanks for the quick reply!
If I didn't get it work, the issue about zero padding may have been solved by line 48、63、64?

**Comment by andi611** [comment]
> Thanks for the quick reply!
> If I didn't get it wrong, the issue about zero padding may have been solved by line 48、63、64?

Line 63, 64 are for logging, you have to apply line 48 to line 59 (loss).

**Comment by toco2270853** [comment]
I got it!
I will add these code before loss calculation and see the result, thanks.

    ignore = self.objective.ignore_index
    for i in range(labels.shape[0]):
        labels[i, lengths[i].item():] = ignore
