### ISSUE TITLE
how to regiester customized upstream models

### ISSUE THREAD

**Issue by jasonppy** [s3prl/s3prl#185]
Hi,

I'm trying to register my own model to score it on the SUPERB benchmark. However, I encountered some problems.

It's mainly that I don't know how to make s3prl.hub to recognize my model. I understand that there is already README https://github.com/s3prl/s3prl/blob/master/s3prl/upstream/example/README.md for this, but I still have a few questions:

(I installed this toolkit by git clone and then pip install -e ./)

1. in the above link, the `expert.py` and `hubconf.py` file are in `./upstream/example/`, and then `python3 run_downsteam.py ... -u customized_upstream ...`, which can link the model in `./upsteam/example/` with name `"customized_upstream"`, I wonder why this is the case

2. suppose I want to add my model `"my_model"` to `s3prl.hub`, how do I do that? I've tried adding a folder `"my_model"` in `./upstream` with `expert.py` and `hubconf.py` in the folder, but it didn't work

3. in this link https://github.com/s3prl/s3prl/blob/master/s3prl/upstream/README.md, it says that the forward function in upsteam model needs to output a dictionary that contains at least two keys: "last_hidden_state" and "hidden_states", I wonder how are they used in downstream tasks respectively (which one is used? how to specify which one I want to use?). 

4. At the same time, in all folders in `./upstream/` (e.g. `apc`, `decoar2`, `wav2vec2` etc.), the forward methods in expert.py all return dictionary with only one key: `"default"`, I wonder how this is related to `"last_hidden_state"` and `"hidden_states"`, and why these models don't follow the requirement?

Thanks for your time and patience.

**Comment by leo19941227** [comment]
Hi @jasonppy !!

Thanks for all the questions, I am happy to help.

1. You can check the **s3prl/s3prl/hub.py** file where we collect all entries defined in the **hubconf.py** under each upstream folder. This format is following the hubconf format defined by torch.hub, and we also expose these collected entries in **s3prl/hubconf.py**
2. Can you provide me the example files under your my_model folder?
3, 4. The dark magic is done by `s3prl/s3prl/upstream/interface.py:UpstreamBase`. Since I found that it is convenient to use hooks to capture all the hidden states inside a model without changing the existing model's forward code to ensure correctness. So I implemented UpstreamBase as a convenient helper to register hooks where it will add the **last_hidden_state** and **hidden_states** keys after the forward of `UpstreamExpert` by hook-captured hidden states. However you can always directly return these two keys in `UpstreamExpert` without using the complicated `UpstreamBase`.

Hope these help with your questions, and feel free to open PR if you would like to register new pretrained models :)

**Comment by jasonppy** [comment]
Perfect, my problems are all solved!

Thanks for the great toolkit
