### ISSUE TITLE
How to get embeddings from "Encoder" and "Context" parts of pretrained wav2vec?

### ISSUE THREAD

**Issue by happypanda5** [s3prl/s3prl#232]
Hello @leo19941227 thanks a lot for the s3prl toolkit

Can you please guide me how to get the embeddings from "Encoder" and "Context" parts of pretrained wav2vec?

In fairseq, one can use feature_extractor and feature_aggregator.

For example in fairseq (https://github.com/pytorch/fairseq/tree/main/examples/wav2vec#example-usage)

`wav_input_16khz = torch.randn(1,10000)`
`z = model.feature_extractor(wav_input_16khz)`
`c = model.feature_aggregator(z)`

**How do we get the embeddings for z and c with s3prl?**

Thank you

**Comment by happypanda5** [comment]
Thanks, I'll check it out

**Comment by leo19941227** [comment]
`hidden_state_0` is the output of the Conv feature encoder so it should be the z vector.
`hidden_state_12` is the output of 12 layers of transformer blocks so it should be c vector.
However, in my experience, you will not get satisfied performance on this two features since they are always not the best layer for any task in SUPERB. The well-performing layers are located at the middle layers of wav2vec2.
On the other hand, the c and z vectors are the jargon only in wav2vec, and wav2vec2 is only evaluated with finetuning the whole model. So, it is reasonable these two features are not good in wav2vec2.
I would suggest to weighted-sum all the layers of features to get good results.

**Comment by GuangkeChen** [comment]
Hi, could you give an example of how to weighted-sum all the layers of features? In the paper of SUPERB, the authors said "We run Dynamic Time Warping[40] on all hidden states separately with standard distance functions and obtain a score for
each query-document pair." I do not understand this well.

**Comment by leo19941227** [comment]
Hi,

weighted sum all the layers of features follows what ELMO did, which is a quite standard way.
For DTW since it is not trainable, hence we run DTW layer by layer to find the best layer containing zero-resource (non trainable) content information.
