### ISSUE TITLE
Why VQ-Wav2vec extracted feature length not match to wav_length//stride_size?

### ISSUE THREAD

**Issue by MingjieChen** [s3prl/s3prl#266]
Hello, 

I found the length of features extracted from VQ-Wav2vec is not equal to wav_length//stride_size.

As mentioned in the paper, stride_size is 10ms (160), window_size is 30ms (480). 
Is there any way to make the extracted features have the length of wav_length//160? 
Because it will be helpful to align VQ features to phone labels or other framewise labels.

I tried to pad wav with 240 at each side, but it is not a solution.

Thanks

**Comment by unilight** [comment]
Sorry, I don't understand your question -- can you provide an example? What do you mean by "length of features extracted from VQ-Wav2vec is not equal to wav_length//stride_size"?

**Comment by leo19941227** [comment]
I think this is related to the issue @unilight once asked me, that even if you give vq-wav2vec a 16000-sample waveform, it does not give you 16000 / 160 = 100 timestamp representation. We found out this is due to the Conv feature extractor in vq-wav2vec (or the entire wav2vec series) does not have proper padding, so that the trailing waveform samples (which can't form an entire window) are dropped and lead to fewer timestamps for some utterances.
