### ISSUE TITLE
facing installation issue with importing hub from s3prl

### ISSUE THREAD

**Issue by rimitalahiri92** [s3prl/s3prl#294]
<img width="974" alt="Screen Shot 2022-03-09 at 7 23 34 PM" src="https://user-images.githubusercontent.com/46938927/157582474-410bc329-e60b-43f1-b129-323aee81f308.png">
I am facing this error while running the upstream model for a new downstream task. Seems like a conflict between python3 version, numpy and numba.
I am using python 3.9, numpy 1.20.0, numba 0.55.1...please let me know if anyone has faced similar issues with this repo.

**Comment by sicnu-long** [comment]
Hi, I'm encounter the same problem as you. This is because dtw-python==1.1.6 requires numpy>=1.22 under python 3.9, but the installation of s3prl requires numpy>=1.19.5,<=1.21, so it causes a conflict. I put . /s3prl/downstream/quesst14_dtw to solve the problem, so that when importing the hub, quesst14_dtw will not be imported, and then dtw will not be imported either. If you don't use downstearm/quesst14_dtw then everything is fine!

**Comment by sicnu-long** [comment]
Hi, I'm encounter the same problem as you. This is because dtw-python==1.1.6 requires numpy>=1.22 under python 3.9, but the installation of s3prl requires numpy>=1.19.5,<=1.21, so it causes a conflict. I remove ./s3prl/downstream/quesst14_dtw to solve the problem, so that when importing the hub, quesst14_dtw will not be imported, and then dtw will not be imported either. If you don't use downstearm/quesst14_dtw then everything is fine!

**Comment by rimitalahiri92** [comment]
Hi, just a quick question, I have removed the quesst14_dtw module, still I keep on having the same bug....seems like it is there in the miniconda environment that I am using, do you mind sharing how do you install s3prl without the quesst14_dtw downstream module...thanks a lot for your help...:)

**Comment by sicnu-long** [comment]
Maybe you could try  to install it again, you need run ‘pip install -e . /’ in the ’s3prl‘ directory. For some reason, my installation process is complicated and may not be very helpful to you.

**Comment by rimitalahiri92** [comment]
I used the same technique that you mentioned and got rid of the error. Thanks for the help..:)
