### ISSUE TITLE
Query regarding custom data preparation for getting  frame level outputs in downstream tasks(ex. speaker ID)

### ISSUE THREAD

**Issue by rimitalahiri92** [s3prl/s3prl#308]
Hello,

Is there any specific downstream task which deals with frame level outputs(ex. speaker ID). Voxceleb_frame_level task is not very clearly explained, it will be great to get some help on how to prepare a custom dataset to feed in to the network and get framelevel outputs and corresponding metrics.

**Comment by hank0316** [comment]
Hi, 

I think you can try to split your data into many frames, and do padding to make length of each frame be the same if needed. Then in the `__getitem__()` and `collate_fn()`, return a tensor consists of frames. 

As for the downstream model, you should project the features output from upstream to the correct dimension, i.e. number of frames in your original data. For example, if the original data can be split into 10 frames, your output dimension should be 10.

**Comment by andi611** [comment]
> Hello,
> 
> it will be great to get some help on how to prepare a custom dataset to feed in to the network and get framelevel outputs and corresponding metrics.

Hi @rimitalahiri92 , please check out this [dataset](https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/phone_linear/dataset.py) for frame-wise phoneme classification, it takes speech frames as input, and the output targets are the corresponding frame-level phonemes. 

The metrics and loss for this kind of frame level outputs are calculated as follow: [codes](https://github.com/s3prl/s3prl/blob/4fcd8a980ba624159f7773bc08b768b47f948de6/s3prl/downstream/phone_linear/expert.py#L148-L158)

**Comment by leo19941227** [comment]
Hi,

The design of the current codebase is not ideal since it entangles the data-dependent corpus & task-level logics together in a single Dataset class. So usually you must change the Dataset code to enable new data. Sorry for the inconvenience. As a temporary solution you can refer to @andi611's solution on how to tweak an existing dataset (for frame-level phoneme classification) to fit your need.

As for the generic data-independent dataset classes like UtteranceLevelClassification or FrameLevelClassification, this is what we are working on now internally and will be released soon. We wish to enable much easier data switch for a task after this release. Please stay tuned!

I am closing this issue for now. Feel free to re-open it if you have more questions. Thanks!
