### ISSUE TITLE
fbank + mean pooling results in the same prediction for every data instance

### ISSUE THREAD

**Issue by Ethan07902050** [s3prl/s3prl#316]
Hello

I tried to run a keyword spotting experiment according to the documentation `downstream/docs/superb.md`.

```
python3 run_downstream.py -n ExpName -m train -u fbank -d speech_commands
```

However, the output tensors after mean pooling layer are identical for every data instance, as shown in the images below, resulting in the same predictions.

Tensors before mean pooling layer
![input_tensor](https://user-images.githubusercontent.com/48169870/163330551-25111662-47a1-461f-af65-4f7a199cc647.jpg)

After mean pooling layer
![pooled_tensor](https://user-images.githubusercontent.com/48169870/163330583-0a42e339-89ad-4486-ba70-7c34ea7bb535.jpg)

Similar outcomes can be observed for other classification tasks, such as speaker identification and intent classification, if the upstream is fbank and the downstream model contains mean pooling layer.

The reason might be the cmvn procedure specified in `upstream/baseline/fbank.yaml`. If we change the config to `upstream/baseline/fbank_no_cmvn.yaml` by `-u fbank_no_cmvn`, the outputs look much more reasonable.
![pool_no_cmvn](https://user-images.githubusercontent.com/48169870/163330769-d01be62d-3d7a-41ab-8b9a-2c1bc5d458bd.jpg)

Perhaps `-u fbank` should be changed to `-u fbank_no_cmvn` for those downstream tasks in the documentation?

**Comment by leo19941227** [comment]
Hi,

Yes, this is correct, and this is why we add `fbank_no_cmvn` afterward.
CMVN is usually useful for frame-level recognition tasks like PR, ASR, so we adopt it at the beginning.
However, later we find this is not reasonable if we apply mean-pooling on top of it after the SUPERB paper is published, so `fbank_no_cmvn` is further tested.
To strictly reproduce the paper you should use `fbank` for all the tasks. To avoid CMVN for simple mean pooling tasks (SID, ER, KS, IC), you can replace with `fbank_no_cmvn`. Here are my results for `fbank_no_cmvn` after testing:

| method | SID | ER | KS | IC |
| - | - | - | - | - |
| fbank_no_cmvn | 20.058 | 48.236 | 41.382 | 9.649 |

Despite the numbers are different, it does not affect our final conclusion about the huge superiority of SSL features over acoustic features. Hence we did not revise the paper to keep the consistency since it is already published.
This subtle difference is planned to be detailed in the follow-up journal, so you can choose which one you would like to study for now.
