### ISSUE TITLE
ImportError: cannot import name 'EMAModule' from 'fairseq.modules' (/opt/conda/lib/python3.7/site-packages/fairseq/modules/__init__.py)

### ISSUE THREAD

**Issue by maziye-azad** [s3prl/s3prl#348]
hi, while i'm trying to import my model from s3prl i face this error:
ImportError: cannot import name 'EMAModule' from 'fairseq.modules' (/opt/conda/lib/python3.7/site-packages/fairseq/modules/__init__.py)
i didn't have this problem before.
whats the problem?

**Comment by leijue222** [comment]
I also encountered this problem, how can I solve it?

**Comment by leijue222** [comment]
> Hi, this is due to the fairseq version. We have fixed this in the latest master, please pull the lastest master and re-install S3PRL It should work after re-installation

Thanks!
By the way, here's a warning about kaldi, do I need to install kaldi?

```
################################################################################
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profile)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################
```

**Comment by leo19941227** [comment]
No you don't need kaldi. This is just because some of our task use kaldiio to load files in kaldi format. But it is very rare you will need this function.

**Comment by leijue222** [comment]
Hi, @leo19941227 .
Due to my own machine, I cannot use `pip install -e ./` to install the environment. So I had to manually install every environment dependency. 
But I can't git clone the correct version of fairseq (Version: 1.0.0a0+b5a039c).
https://github.com/s3prl/s3prl/blob/540a4f86e9f099b240c314a56ff80b069e91d4cd/setup.py#L60
`git clone https://github.com/facebookresearch/fairseq.git` the version wil be 0.11.0
`git clone https://github.com//pytorch/fairseq.git@b5a039c292facba9c73f59ff34621ec131d82341` the requested URL returned error: 400
So what is the correct code URL address for fairseq version 1.0.0a0+b5a039c？
(I'm sorry that environmental issues have bothered you many times.)
