### ISSUE TITLE
KeyError: 's3prl.upstream'

### ISSUE THREAD

**Issue by vinayentc31** [s3prl/s3prl#349]
Hi, 

I am working on notebook - **ESPNET Noisy SLU Demonstration**

https://colab.research.google.com/drive/14nCrJ05vJcQX0cJuXjbMVFWUHJ3Wfb6N?authuser=1

for the cell 13 I am getting error - KeyError: 's3prl.upstream'

This part of code - 
####
from espnet2.bin.asr_inference import Speech2Text
speech2text_fsc = Speech2Text.from_pretrained(
    asr_train_config="/content/fsc_model/exp/asr_train_asr_hubert_transformer_adam_specaug_raw_en_word/config.yaml",
    asr_model_file="/content/fsc_model/exp/asr_train_asr_hubert_transformer_adam_specaug_raw_en_word/valid.acc.ave_5best.pth",
    # Decoding parameters are not included in the model file
    nbest=1
)
##########

Can you please help. Thanks.

**Comment by leo19941227** [comment]
Sure, let me check

**Comment by vinayentc31** [comment]
> Sure, let me check

Thanks a lot, Updated the URL.

**Comment by leo19941227** [comment]
![image](https://user-images.githubusercontent.com/33196053/171836218-e187e889-6d12-4180-817c-29c0864efc06.png)

Hey, when I want to reproduce the issue and click the `run all` button, I encounter this error which I think is not related to S3PRL. Could you help to adjust to colab to directly reproduce the S3PRL error?

Many thanks!!

**Comment by leo19941227** [comment]
Oh never mind, after I run the colab again it works now. It seems the first `run all` might crash somehow. Might be an useful information to you

**Comment by leo19941227** [comment]
I think it will work after switching to an older version S3PRL. Since S3PRL now depends on fairseq, hence you will need the correct fairseq version (fixed in our setup.py) to make S3PRL work. This fix also appear in the latest ESPNet installation:

https://github.com/simpleoier/espnet/blob/74965106a6ca561545f4821812e35eca0dd7e4b4/tools/installers/install_s3prl.sh#L54-L57

Either switching to an older commit of S3PRL, or upgrade the fairseq to align with the commit in our setup.py. I think both ways work. In your colab I try to use an older S3PRL and now it works

![image](https://user-images.githubusercontent.com/33196053/171840450-fc03803b-8ba5-4ddc-9a91-b730bd12bff0.png)

![image](https://user-images.githubusercontent.com/33196053/171840484-7418b8e7-400a-417e-bea4-41415b7e38c8.png)

![image](https://user-images.githubusercontent.com/33196053/171840512-839df90e-f46f-4c0e-8a3e-dbb7a60e2acb.png)

**Comment by vinayentc31** [comment]
Thanks a lot, this works. Closing the issue.
