### ISSUE TITLE
 Tensorboard question

### ISSUE THREAD

**Issue by gyccc000** [s3prl/s3prl#354]
If I use a remote server, how can I watch my training loss with a tensorboard ?

Thank you very much !

**Comment by leo19941227** [comment]
Hi,

Despite this is not a S3PRL-related issue, I would recommend you to use `rsync` to sync between two directories (remote & local), here is an example:

```
rsync -avP leo@140.112.21.12:~/remote/tensorboard ./local/tensorboard
```

And then, launch the tensorboard on your local machine.
Usually, you can only directly launch the tensorboard on the remote computer if you have quite enough permission on it since launching server is usually a dangerous move so usually it is not allowed for a cluster user. If you have a remote computer your own (you are the admin), and you also have a public IP for that computer (I believe this is harder), then you can launch tensorboard directly on the remote computer.

**Comment by leo19941227** [comment]
Note that the command I give you will ignore the already copied files and only copy the new/updated files, so usually `rsync` is much more faster than `scp` directories.
