### ISSUE TITLE
Pypi installation

### ISSUE THREAD

**Issue by franp9am** [s3prl/s3prl#367]
Is there a reason why this line is commented? https://github.com/s3prl/s3prl/blob/master/setup.py#L179

When I try to install the project directly from pypi (`pip install s3prl`) , then I cannot import anything, and am getting error from project-module imports such as `from pretrain.mockingjay.dataset import ...`. It would rather see `from s3prl.pretrain...`

(EDIT) -- but after uncommenting L179, import still fail due to relative imports in `upstream` that try to reach the "main" folder -- for instance, `from ..interfaces import UpstreamBase`

I think the easiest solution would be to write everywhere the full path `from s3prl.pretrain....`.Or not?

**Comment by leo19941227** [comment]
I guess the problem might due to that when you checkout the master branch, it is not directly reflecting the code in our PyPi package. So might be hard to debug the PyPi behavior. This can be avoided in our new release. Now our PyPi package has the complete pipeline to test and have tags on GitHub to checkout which can directly reflect the code in the PyPi package. Also, the `setup.py` is greatly refined so I believe this issue is resolved.
