### ISSUE TITLE
Why don't we have a ASR and PR task for libri-other? Just curious. 

### ISSUE THREAD

**Issue by raotnameh** [s3prl/s3prl#446]

**Comment by leo19941227** [comment]
Just to start from an easier condition. Since back then when we just start to developed SUPERB, many models are actually pre-trained only on LibriSpeech `train-clean-100` and `train-clean-360`. So we just evaluate on the clean condition. I agree with you that this looks out-of-date from today's point of view, and the future development of SUPERB might move on to noisy and fewshot condition. Thanks for the interest.

**Comment by raotnameh** [comment]
@leo19941227 How much time will it take to just add the Libri-other for testing purposes only?
