### ISSUE TITLE
downsample

### ISSUE THREAD

**Issue by Qinnns** [s3prl/s3prl#486]
How is the downsampling rate calculated for each model?
self.downsample_rates

**Comment by chenjoachim** [comment]
The downsampling rate depends on hyperparameter "stride" in the CNN layer of the encoder of an upstream model. Take HuBERT as an example, it used seven 512-channel layers with strides [5,2,2,2,2,2,2] and kernel widths [10,3,3,3,3,2,2]. This results in a downsample rate of 5*2*2*2*2*2*2=320. You can also get the downsample rate using get_downsample_rates() from upstream models.
@dlion168

**Comment by dlion168** [comment]
> The downsampling rate depends on hyperparameter "stride" in the CNN layer of the encoder of an upstream model. Take HuBERT as an example, it used seven 512-channel layers with strides [5,2,2,2,2,2,2] and kernel widths [10,3,3,3,3,2,2]. This results in a downsample rate of 5_2_2_2_2_2_2=320. You can also get the downsample rate using get_downsample_rates() from upstream models. @dlion168

What do you mean "5_2_2_2_2_2_2=320" ?
Also, some models like TERA don't have CNN layer, how to determine their  downsample rate?

**Comment by chenjoachim** [comment]
Sorry for the typo in the previous comment. I have fixed that now.
For TERA, Mockingjay, and some other models without CNN layer, the downsample rate depends on the downsample rate of the feature which the model is pre-trained on since its pre-training method is comparing the prediction with the feature directly. (You can refer to issue #96) 
A special case is FBank. Usually, a stride of 10ms is chosen to get a better view of the signal. Therefore, there are 100 sample per second after FBank, and the downsample rate is 160.
