### ISSUE TITLE
about mosei?

### ISSUE THREAD

**Issue by LM-MSA** [s3prl/s3prl#487]
The link to the original CMU-MOSEI dataset http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSEI.zip is no longer available, could you please share it?

**Comment by bagustris** [comment]
It is better to contact the dataset owner directly (http://multicomp.cs.cmu.edu/) since it has nothing to do with this S3PRL toolkit.

**Comment by leo19941227** [comment]
Yeah, we do not have a copy of the raw CMU-MOSEI

**Comment by bagustris** [comment]
@LM-MSA 
I have a raw copy of CMU-MOSEI, but I am afraid it will infringe on their license if I share it. You can also open an issue in their official repo for CMU-MOSEI: https://github.com/CMU-MultiComp-Lab/CMU-MultimodalSDK.

**Comment by abwilf** [comment]
Hi there, sorry we are not permitted to share the raw videos because of licensing concerns. The processed features are all available on the immortal page, though!

**Comment by bagustris** [comment]
@abwilf 

Thanks for that information. Instead of the processed feature, can we share the processed audio? One of the goals is to observe which acoustic feature is related to sentiment/emotion via self-supervised learning; hence it will be difficult to build model with only a single processed feature (covarep) only.
