### ISSUE TITLE
Potential SpecAug Issue

### ISSUE THREAD

**Issue by xt0r3-Cambridge** [s3prl/s3prl#529]
# Bug report

**Describe the bug**
SpecAug in SUPERB seems to be operating on the upstream features rather than the input audio.
```
if specaug:
    features, _ = specaug(features)
```

**Expected behavior**
If I'm not mistaken, SpecAug is supposed to be called on the *raw input features* to the upstream model instead of its output features like so:
```
if specaug:
    wavs, _ = specaug(wavs)
```

If I am mistaken, can someone please explain the reasoning behind this?
@GiscardBiamby seems to be the original contributor, maybe he knows more about this than me.

**Comment by andi611** [comment]
@xt0r3-Cambridge Hello,

In SUPERB, the upstream features are used as the input features to the downstream models:
`wavs -> upstream model -> upstream features -> specaug -> downstream model`

Additionally, the upstream models are frozen and not fine-tunable so that you can view them as feature extractors, 
and the upstream features are essentially raw input features to the downstream model.

Finally, SpecAug operates on any 2D input (Mel spectrograms, hidden vectors, upstream features, etc), and not 1D input (wavs).

Hence, the current behavior is as expected.
