### ISSUE TITLE
Performance difference between converted models and official models

### ISSUE THREAD

**Issue by wenjie-p** [s3prl/s3prl#544]
Hi, thanks for providing this wonderful benchmark for ssl models! I noticed on we have two kinds of ssl models on huggingface website, one is from the official repository like [facebook/hubert-base](https://huggingface.co/facebook/hubert-base-ls960) while the other is the converted models by [s3prl](https://huggingface.co/s3prl/converted_ckpts/tree/main).

I am evaluating the above two hubert base model on query-by-example task using the last layer's output, but found a different performance, which is suprised to me:

1) evaluated with the facebook repo: `python run_downstream.py -u hf_hubert_custom -k facebook/hubert-base-ls960 ...`. I get the maxTWV of 0.06696204.

2) evaluated with the s3prl converted mdoels: `python run_downstream.py -u hubert` And the maxTWV is 0.07005093.

Can you please tell me why this performance gap existed as the two results are assumed to be the same/similar.

Thanks in advance!

**Comment by leo19941227** [comment]
Hi,

Please use the converted models which are simply the official Fairseq models with a few format changes without touching the weights.
The Hugginface models produce slightly different frozen representation values due to their re-implementation in my personal experience.
The difference might not be noticeable when fine-tuning the SSL model or using a trainable downstream model.
However, it can cause significant difference when running DTW algorithm directly on the frozen representation, as shown by your QbE result.

Hence, the difference between two implementations is somewhat expected, and I would suggest to stick to the Fairseq version when reproducing the SUPERB result.
(Please note that I do not indicate that there is any correctness issue.)
