### ISSUE TITLE
About generating custom dataset

### ISSUE THREAD

**Issue by suzhenghang** [s3prl/s3prl#60]
Hi @andi611 ,  I am a newcomer to the audio field (Actually a cver..). I wonder whether i should change the default  parameters in utility/audio.py such as sample_rate = 16000 when processing my own custom dataset? Thanks in advance.

**Comment by andi611** [comment]
If your dataset is of sample rate 16000, then you don't have to change it.
You can check the sample rate through this [function](https://pytorch.org/audio/stable/torchaudio.html#torchaudio.load):
```
wav, sample_rate = torchaudio.load('example_audio_file.flac')
```

**Comment by leo19941227** [comment]
Currently we focus on only supporting sample rate 16000. This is because the mainstream sample rate used in Self-supervised Speech community is 16000 and we stick to this convention for the fair comparison between pretraining methods.

If you wish to pretrain your own new self-supervised models, feel free to do the resampling in dataloader (yet we do not make this configurable for now.) and stick to this setting when using the pretrained model in your downstream task.

While if you wish to use the already pretrained checkpoint, currently all the available pretrained checkpoints are trained by wavs in 16000 Hz. That is, one has to stick to sample rate 16000 for the good downstream performance.

Hope this help!
