### ISSUE TITLE
[Feature Request] Speaker verification downstream with ge2e objective

### ISSUE THREAD

**Issue by SolomidHero** [s3prl/s3prl#74]
Hello! We have `speaker_linear_frame_libri` as speaker verification downstream task. Can we also have downstream task for that problem in more generalized way like in ge2e loss and training ([paper](https://arxiv.org/pdf/1710.10467.pdf))?

**Comment by pohanchi** [comment]
Hi, Can you go more detail about what you want ? Since frame-level speaker verification sound strange, do you mean speaker verification in LibriSpeech ? 

We had implemented downstream voxceleb2-ge2e for speaker verification , you can follow there if you just want a speaker verification task. To let us know if you have advance question for that.

**Comment by SolomidHero** [comment]
Hi, speaker verification task can be quite useful to make linguistically independent embeddings of speakers. But datasets used for training or tuning may be really different. In my example I am working with multilingual data and want to tune models for being robust to source languages.

I also have data which look like librispeech dataset's tree.

So I think it would be useful to have speaker verification task on libri with either ge2e or amsoftmax losses, because
- current `voxceleb_ge2e` has many things to adapt
- averaging representations after existing `speaker_linear_frame_libri` task would have lower quality (as being speaker embedding), in my opinion

**Comment by pohanchi** [comment]
It do not have much different structure between these two dataset (Their structure is almost equal to each other.) (voxceleb and librispeech).

If you still want, I can build one for librispeech soon. But I suggest that you definitely can modify a little code to fit on your project for currently structure.
[either am-softmax or ge2e]

**Comment by leo19941227** [comment]
Hi,

Sorry that we will not support am-softmax or ge2e for LibriSpeech.
Since in our experiments we found that speaker recognition using LibriSpeech is way easier than VoxCeleb, and we will not continue to evaluate representation with LibriSpeech in the future. So the `speaker_linear_frame_libri` series under the `downstream` folder is just left for legacy reason.
Indeed averaging representation will degrade the speaker performance, however in our previous speaker experiments on LibriSpeech we are targeting at evaluating the quality of representation instead of achieving numbers as high as possible.
However, pull request for adapting am-softmax / ge2e for LibriSpeech is still very welcome.
Hope this answer your question.

Sincerely,
Leo
