### ISSUE TITLE
tqdm.auto instead of tqdm

### ISSUE THREAD

**Issue by SolomidHero** [s3prl/s3prl#76]
Hi! Is it possible to make scripts using loop visualisation with tqdm more platform independent? For now, `runner.py` train method uses nested tqdm, which results in wrong output with many lines (for jupyter notebooks):
```
...
overall:  24% 23765/100000 [42:32<2:06:44, 10.02it/s]
overall:  24% 23767/100000 [42:32<2:02:27, 10.38it/s]
overall:  24% 23769/100000 [42:32<2:09:15,  9.83it/s]
overall:  24% 23771/100000 [42:33<2:04:34, 10.20it/s]
overall:  24% 23773/100000 [42:33<2:03:56, 10.25it/s]
overall:  24% 23775/100000 [42:33<2:01:58, 10.42it/s]
overall:  24% 23777/100000 [42:33<2:15:19,  9.39it/s]
overall:  24% 23779/100000 [42:33<2:05:46, 10.10it/s]
overall:  24% 23781/100000 [42:34<2:19:19,  9.12it/s]
overall:  24% 23782/100000 [42:34<2:18:51,  9.15it/s]
overall:  24% 23783/100000 [42:34<2:22:18,  8.93it/s]
overall:  24% 23784/100000 [42:34<2:19:59,  9.07it/s]
overall:  24% 23786/100000 [42:34<2:14:33,  9.44it/s]
overall:  24% 23787/100000 [42:34<2:13:22,  9.52it/s]
train: 100% 231/231 [00:24<00:00,  9.49it/s]

overall:  24% 23789/100000 [42:35<4:15:25,  4.97it/s]
overall:  24% 23790/100000 [42:35<3:46:34,  5.61it/s]
overall:  24% 23791/100000 [42:35<3:18:58,  6.38it/s]
overall:  24% 23793/100000 [42:36<2:55:28,  7.24it/s]
overall:  24% 23794/100000 [42:36<2:43:26,  7.77it/s]
overall:  24% 23796/100000 [42:36<2:25:14,  8.74it/s]
overall:  24% 23798/100000 [42:36<2:22:38,  8.90it/s]
overall:  24% 23800/100000 [42:36<2:14:05,  9.47it/s]
overall:  24% 23802/100000 [42:36<2:03:32, 10.28it/s]
overall:  24% 23804/100000 [42:37<2:02:08, 10.40it/s]
overall:  24% 23806/100000 [42:37<2:07:54,  9.93it/s]
overall:  24% 23808/100000 [42:37<2:19:42,  9.09i
```

This behaviour was seen on google colab.

Possible solution was mentioned in https://github.com/tqdm/tqdm/issues/375 issue.

**Comment by leo19941227** [comment]
Hey!

Thanks for the suggestion, I will check this later.

**Comment by leo19941227** [comment]
Hey,

I am sorry that after changing to `tqdm.auto`, the program sometimes crashes on the computational server in our lab, resulting in the issue similar to [this](https://github.com/tqdm/tqdm/issues/613?fbclid=IwAR2AZxe1RajBgVqmkhzL6piqq2LEirs4mKJey5RMDKSrZ5-Ov_fcq6f40Iw). Despite that the issue is reported to be resolved by upgrading to the latest tqdm version, we still encounter crashes after upgrading to the latest version.
Hence, we decide to revert back to the original style. We are sorry for your inconvenience, and you can always cherry pick this [commit](https://github.com/s3prl/s3prl/commit/87896d61407b0c1089fa95ef0384bf2497fbfe26) if you want a quick fix to use `tqdm.auto`.

Sincerely,
Leo
